import { AvatarConfig, RigParams, PresetAvatar } from './types';

/** Neutral rig calibration — every tracking/animation frame starts from here. */
export const INITIAL_RIG: RigParams = {
  eyeLOpen: 1.0,
  eyeROpen: 1.0,
  mouthOpen: 0.0,
  mouthForm: 0.5,
  eyebrowY: 0,
  pupilX: 0,
  pupilY: 0,
  angleX: 0,
  angleY: 0,
  angleZ: 0,
  breath: 0,
  bodyX: 0,
  tongueOut: 0.0,
};

/**
 * Built-in starter characters. Each `id` is a stable localization key — the
 * matching `<id>_name` / `<id>_lore` entries live in src/i18n/{en,uk}.ts.
 * The `name`/`lore` baked into `config` are the authored fallback used when no
 * translation exists (e.g. for custom or AI-generated avatars).
 */
export const PRESETS: PresetAvatar[] = [
  {
    id: 'cyber-neko',
    name: 'Мія (Cyber Neko)',
    config: {
      skinColor: '#f5f3ff',
      eyeColor: '#06b6d4',
      pupilStyle: 'round',
      pupilColor: '#f43f5e',
      eyebrowStyle: 'normal',
      eyebrowColor: '#4f46e5',
      hairStyleBang: 'side',
      hairStyleBack: 'drill-tails',
      hairColor: '#4f46e5',
      hairHighlightColor: '#a855f7',
      clothingStyle: 'cyber-armor',
      clothingColor1: '#111827',
      clothingColor2: '#22d3ee',
      accessoryStyle: 'neko-ears',
      accessoryColor: '#f43f5e',
      backgroundStyle: 'gaming',
      name: 'Мія',
      lore: 'Кібернетична дівчинка-кішка, яка веде стріми з віртуального неонового Токіо. Хоч вона інколи буває забудькувата, її життєрадісність та драйв притягують тисячі глядачів!',
      blushOpacity: 0.25,
      blushColor: '#ff4d6d',
      hasFangs: false,
      earStyle: 'normal',
      hairGradient: 'sunset',
      accessoryGlow: true,
      headSize: 1.05,
      neckWidth: 0.82,
      neckHeight: 0.9,
      shoulderWidth: 0.94,
      clothingPrint: 'cyber',
      activeEmotion: 'smug',
      artStyle: 'anime',
    },
  },
  {
    id: 'vampire-princess',
    name: 'Міцукі (Goth Vampire)',
    config: {
      skinColor: '#fafaf9',
      eyeColor: '#f43f5e',
      pupilStyle: 'heart',
      pupilColor: '#ffe4e6',
      eyebrowStyle: 'thin',
      eyebrowColor: '#18181b',
      hairStyleBang: 'hime',
      hairStyleBack: 'hime-long',
      hairColor: '#18181b',
      hairHighlightColor: '#be123c',
      clothingStyle: 'goth-dress',
      clothingColor1: '#18181b',
      clothingColor2: '#f43f5e',
      accessoryStyle: 'horns',
      accessoryColor: '#f43f5e',
      backgroundStyle: 'dark-studio',
      name: 'Міцукі',
      lore: 'Готична вампірська лоліта, яка замість сну в склепі до світанку затято розгадує головоломки та проходить хардкорні RPG. Обожнює кажанів, чай з журавлини та іклавий рум’янець.',
      blushOpacity: 0.45,
      blushColor: '#e11d48',
      hasFangs: true,
      earStyle: 'pointy',
      hairGradient: 'sunset',
      accessoryGlow: true,
      headSize: 1.08,
      neckWidth: 0.76,
      neckHeight: 0.88,
      shoulderWidth: 0.9,
      clothingPrint: 'cross',
      activeEmotion: 'angry',
      artStyle: 'classic',
    },
  },
  {
    id: 'astral-elf',
    name: 'Луна (Astral Star Elf)',
    config: {
      skinColor: '#f0fdfa',
      eyeColor: '#8b5cf6',
      pupilStyle: 'star',
      pupilColor: '#fef08a',
      eyebrowStyle: 'normal',
      eyebrowColor: '#7c3aed',
      hairStyleBang: 'curly-bangs',
      hairStyleBack: 'wavy',
      hairColor: '#6d28d9',
      hairHighlightColor: '#a78bfa',
      clothingStyle: 'sweater',
      clothingColor1: '#2e1065',
      clothingColor2: '#a78bfa',
      accessoryStyle: 'glasses',
      accessoryColor: '#fef08a',
      backgroundStyle: 'nebula',
      name: 'Луна',
      lore: 'Ельфійська хранителька бібліотеки зіркового світла. Вона обожнює слухати ASMR звуки нічного космосу, ховатися в теплий в’язаний светр і розповідати казки про далекі туманності.',
      blushOpacity: 0.2,
      blushColor: '#ec4899',
      hasFangs: false,
      earStyle: 'elf',
      hairGradient: 'indigo-fade',
      accessoryGlow: false,
      headSize: 1.0,
      neckWidth: 0.8,
      neckHeight: 1.0,
      shoulderWidth: 0.94,
      clothingPrint: 'heart',
      activeEmotion: 'none',
      artStyle: 'classic',
    },
  },
  {
    id: 'anime-idol',
    name: 'Кіра (Crimson Star)',
    config: {
      skinColor: '#fff5f5',
      eyeColor: '#06b6d4',
      pupilStyle: 'round',
      pupilColor: '#0f172a',
      eyebrowStyle: 'thin',
      eyebrowColor: '#e11d48',
      hairStyleBang: 'hime',
      hairStyleBack: 'hime-long',
      hairColor: '#e11d48',
      hairHighlightColor: '#fda4af',
      clothingStyle: 'goth-dress',
      clothingColor1: '#0f172a',
      clothingColor2: '#ffffff',
      accessoryStyle: 'neko-ears',
      accessoryColor: '#e11d48',
      backgroundStyle: 'nebula',
      name: 'Кіра',
      lore: 'Червоноволоса аніме-кішкодівчина в стилі High School DxD. Її шовковисте волосся кольору багряного серця прикрашає грайливий ахоге (пасмо), а сяючі аквамаринові очі та класична школа-самурайка підкорюють серця.',
      blushOpacity: 0.35,
      blushColor: '#f43f5e',
      hasFangs: false,
      earStyle: 'normal',
      hairGradient: 'sunset',
      accessoryGlow: false,
      headSize: 1.04,
      neckWidth: 0.72,
      neckHeight: 0.95,
      shoulderWidth: 0.9,
      clothingPrint: 'heart',
      activeEmotion: 'happy',
      artStyle: 'anime',
    },
  },
  {
    id: 'koneko-dxd',
    name: 'Конеко (White Kitten)',
    config: {
      skinColor: '#fffaf8',
      eyeColor: '#f59e0b',
      pupilStyle: 'round',
      pupilColor: '#3c1e02',
      eyebrowStyle: 'thin',
      eyebrowColor: '#7c2d12',
      hairStyleBang: 'classic',
      hairStyleBack: 'short',
      hairColor: '#e5e7eb',
      hairHighlightColor: '#ffffff',
      clothingStyle: 'maid',
      clothingColor1: '#0f172a',
      clothingColor2: '#ffffff',
      accessoryStyle: 'neko-ears',
      accessoryColor: '#e5e7eb',
      backgroundStyle: 'dark-studio',
      name: 'Конеко',
      lore: 'Срібноволоса дівчина-кішка в стилі легендарної Конеко з High School DxD. Завжди спокійна й незворушна зовні, вона постає перед вами в чарівному готичному костюмі покоївки із шовковистими білими вушками та сяючими золотими очками, що підкорять ваше серце!',
      blushOpacity: 0.4,
      blushColor: '#ff2e55',
      hasFangs: false,
      earStyle: 'normal',
      hairGradient: 'none',
      accessoryGlow: false,
      headSize: 1.05,
      neckWidth: 0.74,
      neckHeight: 0.94,
      shoulderWidth: 0.92,
      clothingPrint: 'heart',
      activeEmotion: 'none',
      artStyle: 'anime',
    },
  },
  {
    id: 'retro-pip',
    name: 'Піп (1930s Rubber Hose)',
    config: {
      skinColor: '#f5efe0',
      eyeColor: '#111111',
      pupilStyle: 'round',
      pupilColor: '#000000',
      eyebrowStyle: 'thick',
      eyebrowColor: '#111111',
      hairStyleBang: 'short',
      hairStyleBack: 'short',
      hairColor: '#18181b',
      hairHighlightColor: '#3f3f46',
      clothingStyle: 'suit',
      clothingColor1: '#111111',
      clothingColor2: '#ffffff',
      accessoryStyle: 'none',
      accessoryColor: '#111111',
      backgroundStyle: 'dark-studio',
      name: 'Піп',
      lore: 'Класичний чорно-білий мультиплікаційний герой епохи 1930-х. Він постійно весело пружинить і коливається під уявні джазові синкопи, носить стильний круглий фрак та робить комічні очі!',
      blushOpacity: 0.15,
      blushColor: '#000000',
      hasFangs: false,
      earStyle: 'pointy',
      hairGradient: 'none',
      accessoryGlow: false,
      headSize: 1.1,
      neckWidth: 0.7,
      neckHeight: 0.85,
      shoulderWidth: 0.85,
      clothingPrint: 'cross',
      activeEmotion: 'shocked',
      artStyle: 'retro',
    },
  },
];

/** Default starting avatar. */
export const DEFAULT_CONFIG: AvatarConfig = PRESETS[0].config;

type PresetStats = { presetStats: Record<string, string> };

/**
 * Resolve a built-in preset's localized name + lore by its id.
 * Returns null when `key` is null/unknown (custom or AI-generated avatar),
 * letting callers fall back to the config's own name/lore.
 */
export function localizePreset(key: string | null, t: PresetStats): { name: string; lore: string } | null {
  if (!key) return null;
  const stats = t.presetStats;
  const name = stats[`${key}_name`];
  const lore = stats[`${key}_lore`];
  if (name && lore) return { name, lore };
  return null;
}
